### ISSUE TITLE
[BUG] DeSEQ2 1.3.7 says columns don't exist but they do.

### ISSUE THREAD

**Issue by hannahle** [latch-verified/diff-exp#2]
To reproduce, see the following count and design:

- /[Hannah's Test Data] - Count Tables/hammer_count_table.csv
- /[Hannah's Test Data] - Count Tables/phenodata/csv/Counts - hammer_phenodata.csv

It seems to fail on samples with a "-" in name (`SRX020091-3`, `SRX020088-90`, `SRX020094-7`, and `SRX020098-101`).

**Comment by kennyworkman** [comment]
v1.3.19 resolves
